package com.udpmail.server.view;

import com.udpmail.server.listener.ServerEventListener;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.net.InetAddress;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ServerFrame extends JFrame implements ServerEventListener {
    private static final Color NAVY=new Color(0x071B41),PRIMARY=new Color(0x1477F8),SUCCESS=new Color(0x16A34A),ERROR=new Color(0xEF3340),MUTED=new Color(0x64748B),BORDER=new Color(0xD7E1EF),BG=new Color(0xF5F8FC);
    private final JLabel state=new JLabel("ĐÃ DỪNG"),accountValue=value("0"),onlineValue=value("0"),emailValue=value("0"),listenStatus=new JLabel("UDP Server sẵn sàng tại cổng 2006"),clock=new JLabel();
    private final JButton start=button("Khởi động",PRIMARY),stop=button("Dừng Server",ERROR),refresh=button("Làm mới",Color.WHITE);
    private final DefaultTableModel users=new DefaultTableModel(new Object[]{"STT","Tên đăng nhập","Địa chỉ IP","Trạng thái","Thời gian đăng nhập"},0){public boolean isCellEditable(int r,int c){return false;}};
    private final DefaultTableModel logs=new DefaultTableModel(new Object[]{"Thời gian","Sự kiện","Thông tin"},0){public boolean isCellEditable(int r,int c){return false;}};
    private Runnable startAction,stopAction,refreshAction;

    public ServerFrame(){
        super("UDP MAIL SERVER");Image windowIcon=IconManager.image("network",32,32,PRIMARY);if(windowIcon!=null)setIconImage(windowIcon);setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(1250,800);setMinimumSize(new Dimension(1000,680));setLocationRelativeTo(null);
        JPanel root=new JPanel(new BorderLayout(0,14));root.setBackground(BG);root.setBorder(new EmptyBorder(18,20,0,20));setContentPane(root);root.add(header(),BorderLayout.NORTH);
        JPanel center=new JPanel(new BorderLayout(0,14));center.setOpaque(false);center.add(metrics(),BorderLayout.NORTH);center.add(tables(),BorderLayout.CENTER);root.add(center,BorderLayout.CENTER);root.add(statusBar(),BorderLayout.SOUTH);
        start.addActionListener(e->runAction(startAction,"Không thể khởi động Server"));stop.addActionListener(e->runAction(stopAction,"Không thể dừng Server"));refresh.addActionListener(e->runAction(refreshAction,"Không thể làm mới dữ liệu"));stop.setEnabled(false);
        Timer timer=new Timer(1000,e->clock.setText("Thời gian hệ thống:  "+LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"))));timer.setInitialDelay(0);timer.start();
    }

    private JComponent header(){
        JPanel panel=new JPanel(new BorderLayout(18,0));panel.setOpaque(false);JPanel brand=new JPanel(new FlowLayout(FlowLayout.LEFT,14,2));brand.setOpaque(false);brand.add(new JLabel(IconManager.load("network",50,50,PRIMARY)));
        JPanel text=new JPanel();text.setOpaque(false);text.setLayout(new BoxLayout(text,BoxLayout.Y_AXIS));JLabel title=new JLabel("UDP MAIL SERVER");title.setFont(new Font("Segoe UI",Font.BOLD,29));title.setForeground(NAVY);JLabel subtitle=new JLabel("Máy chủ quản lý tài khoản và lưu trữ email");subtitle.setFont(new Font("Segoe UI",Font.BOLD,14));subtitle.setForeground(MUTED);text.add(title);text.add(subtitle);brand.add(text);brand.add(Box.createHorizontalStrut(8));styleBadge(false);brand.add(state);panel.add(brand,BorderLayout.WEST);
        JPanel controls=new JPanel(new FlowLayout(FlowLayout.RIGHT,10,4));controls.setOpaque(false);controls.add(infoCard("IP Server",localIp(),IconManager.load("network",23,23,PRIMARY)));controls.add(infoCard("Cổng","2006",IconManager.load("ethernet-port",23,23,PRIMARY)));start.setIcon(IconManager.load("play",19,19,Color.WHITE));start.setIconTextGap(8);stop.setIcon(IconManager.load("square",18,18,Color.WHITE));stop.setIconTextGap(8);start.setPreferredSize(new Dimension(135,50));stop.setPreferredSize(new Dimension(145,50));controls.add(start);controls.add(stop);panel.add(controls,BorderLayout.EAST);return panel;
    }

    private JComponent metrics(){JPanel panel=new JPanel(new GridLayout(1,3,14,0));panel.setOpaque(false);panel.add(metricCard(accountValue,"tài khoản","Tổng số tài khoản người dùng",IconManager.load("users",36,36,PRIMARY)));panel.add(metricCard(onlineValue,"client online","Số client đang kết nối",IconManager.load("monitor",36,36,SUCCESS)));panel.add(metricCard(emailValue,"email đã lưu","Tổng số email trong hệ thống",IconManager.load("mail",36,36,new Color(0x6D3DE8))));return panel;}
    private JComponent metricCard(JLabel number,String label,String description,Icon icon){RoundPanel card=new RoundPanel(new BorderLayout(14,0),Color.WHITE,13);card.setBorder(new EmptyBorder(16,18,16,18));JLabel iconLabel=new JLabel(icon,SwingConstants.CENTER);iconLabel.setOpaque(true);iconLabel.setBackground(new Color(0xEFF5FF));iconLabel.setPreferredSize(new Dimension(68,68));card.add(iconLabel,BorderLayout.WEST);JPanel words=new JPanel();words.setOpaque(false);words.setLayout(new BoxLayout(words,BoxLayout.Y_AXIS));JPanel line=new JPanel(new FlowLayout(FlowLayout.LEFT,10,0));line.setOpaque(false);line.add(number);JLabel name=new JLabel(label);name.setFont(new Font("Segoe UI",Font.BOLD,16));name.setForeground(new Color(0x0847A6));line.add(name);words.add(line);JLabel desc=new JLabel(description);desc.setForeground(MUTED);desc.setFont(new Font("Segoe UI",Font.PLAIN,13));words.add(desc);card.add(words,BorderLayout.CENTER);return card;}

    private JComponent tables(){
        JPanel panel=new JPanel(new GridLayout(2,1,0,14));panel.setOpaque(false);RoundPanel userCard=new RoundPanel(new BorderLayout(0,10),Color.WHITE,13);userCard.setBorder(new EmptyBorder(12,14,14,14));JPanel userTitle=titleRow("Danh sách người dùng",IconManager.load("users",25,25,PRIMARY));refresh.setIcon(IconManager.load("refresh-cw",18,18,new Color(0x0847A6)));refresh.setIconTextGap(8);refresh.setForeground(new Color(0x0847A6));refresh.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BORDER),new EmptyBorder(8,13,8,13)));userTitle.add(refresh,BorderLayout.EAST);userCard.add(userTitle,BorderLayout.NORTH);JTable userTable=table(users);userTable.getColumnModel().getColumn(0).setMaxWidth(65);userTable.getColumnModel().getColumn(3).setCellRenderer(new StatusRenderer());userCard.add(new JScrollPane(userTable),BorderLayout.CENTER);panel.add(userCard);
        RoundPanel logCard=new RoundPanel(new BorderLayout(0,10),Color.WHITE,13);logCard.setBorder(new EmptyBorder(12,14,14,14));logCard.add(titleRow("Nhật ký hoạt động",IconManager.load("file-text",25,25,PRIMARY)),BorderLayout.NORTH);JTable logTable=table(logs);logTable.getColumnModel().getColumn(0).setPreferredWidth(135);logTable.getColumnModel().getColumn(1).setPreferredWidth(115);logTable.getColumnModel().getColumn(2).setPreferredWidth(700);logCard.add(new JScrollPane(logTable),BorderLayout.CENTER);panel.add(logCard);return panel;
    }
    private JPanel titleRow(String text,Icon icon){JPanel panel=new JPanel(new BorderLayout());panel.setOpaque(false);JLabel label=new JLabel(text,icon,SwingConstants.LEFT);label.setIconTextGap(10);label.setForeground(NAVY);label.setFont(new Font("Segoe UI",Font.BOLD,20));panel.add(label,BorderLayout.WEST);return panel;}
    private JTable table(DefaultTableModel model){JTable table=new JTable(model);table.setRowHeight(36);table.setFont(new Font("Segoe UI",Font.PLAIN,14));table.setForeground(NAVY);table.setGridColor(BORDER);table.setSelectionBackground(new Color(0xE5F1FF));table.getTableHeader().setPreferredSize(new Dimension(10,36));table.getTableHeader().setBackground(new Color(0xEAF3FE));table.getTableHeader().setForeground(new Color(0x123B76));table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,13));return table;}

    private JComponent statusBar(){JPanel bar=new JPanel(new BorderLayout());bar.setBackground(Color.WHITE);bar.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(1,0,0,0,BORDER),new EmptyBorder(10,4,10,4)));listenStatus.setForeground(NAVY);listenStatus.setFont(new Font("Segoe UI",Font.PLAIN,14));listenStatus.setIcon(IconManager.load("square",13,13,ERROR));listenStatus.setIconTextGap(12);clock.setForeground(NAVY);bar.add(listenStatus,BorderLayout.WEST);bar.add(clock,BorderLayout.EAST);return bar;}
    private JComponent infoCard(String title,String data,Icon icon){RoundPanel card=new RoundPanel(new BorderLayout(10,2),new Color(0xF0F6FE),11);card.setBorder(new EmptyBorder(8,12,8,12));card.setPreferredSize(new Dimension(150,52));JLabel iconLabel=new JLabel(icon);card.add(iconLabel,BorderLayout.WEST);JPanel text=new JPanel(new BorderLayout(0,1));text.setOpaque(false);JLabel small=new JLabel(title);small.setForeground(MUTED);small.setFont(new Font("Segoe UI",Font.PLAIN,12));JLabel value=new JLabel(data);value.setForeground(NAVY);value.setFont(new Font("Segoe UI",Font.BOLD,15));text.add(small,BorderLayout.NORTH);text.add(value,BorderLayout.CENTER);card.add(text,BorderLayout.CENTER);return card;}

    public void setActions(Runnable startAction,Runnable stopAction,Runnable refreshAction){this.startAction=startAction;this.stopAction=stopAction;this.refreshAction=refreshAction;}
    private void runAction(Runnable action,String errorTitle){if(action==null)return;start.setEnabled(false);stop.setEnabled(false);refresh.setEnabled(false);new SwingWorker<Void,Void>(){protected Void doInBackground(){action.run();return null;}protected void done(){try{get();}catch(Exception e){Throwable cause=e.getCause();JOptionPane.showMessageDialog(ServerFrame.this,cause==null?e.getMessage():cause.getMessage(),errorTitle,JOptionPane.ERROR_MESSAGE);start.setEnabled(true);}finally{refresh.setEnabled(true);}}}.execute();}
    public void onLog(String event,String information){SwingUtilities.invokeLater(()->{logs.insertRow(0,new Object[]{LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")),event,information});if(logs.getRowCount()>500)logs.removeRow(500);});}
    public void onStatsChanged(int a,int o,int e){SwingUtilities.invokeLater(()->{accountValue.setText(String.valueOf(a));onlineValue.setText(String.valueOf(o));emailValue.setText(String.valueOf(e));});}
    public void onUsersChanged(List<UserStatus> data){SwingUtilities.invokeLater(()->{users.setRowCount(0);int index=1;for(UserStatus user:data)users.addRow(new Object[]{index++,user.username(),user.ipAddress(),user.online()?"Online":"Offline",user.loginTime()});});}
    public void onStateChanged(boolean running,int port){SwingUtilities.invokeLater(()->{state.setText(running?"ĐANG HOẠT ĐỘNG":"ĐÃ DỪNG");styleBadge(running);start.setEnabled(!running);stop.setEnabled(running);listenStatus.setText(running?"UDP Server đang lắng nghe tại cổng "+port:"UDP Server đã dừng tại cổng "+port);listenStatus.setIcon(IconManager.load(running?"play":"square",13,13,running?SUCCESS:ERROR));});}
    private void styleBadge(boolean running){state.setOpaque(true);state.setIcon(IconManager.load(running?"play":"square",12,12,running?new Color(0x11863C):ERROR));state.setIconTextGap(7);state.setBackground(running?new Color(0xE5F8EC):new Color(0xFDEBED));state.setForeground(running?new Color(0x11863C):ERROR);state.setBorder(new EmptyBorder(8,14,8,14));state.setFont(new Font("Segoe UI",Font.BOLD,12));}
    private static JLabel value(String text){JLabel label=new JLabel(text);label.setFont(new Font("Segoe UI",Font.BOLD,30));label.setForeground(new Color(0x0847A6));return label;}
    private static JButton button(String text,Color color){JButton button=new JButton(text);button.setFont(new Font("Segoe UI",Font.BOLD,13));button.setBackground(color);button.setForeground(color.equals(Color.WHITE)?NAVY:Color.WHITE);button.setFocusPainted(false);button.setBorder(new EmptyBorder(10,15,10,15));return button;}
    private static String localIp(){try{return InetAddress.getLocalHost().getHostAddress();}catch(Exception e){return "127.0.0.1";}}

    private static final class RoundPanel extends JPanel{private final Color fill;private final int arc;RoundPanel(LayoutManager layout,Color fill,int arc){super(layout);this.fill=fill;this.arc=arc;setOpaque(false);}protected void paintComponent(Graphics graphics){Graphics2D g=(Graphics2D)graphics.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g.setColor(fill);g.fillRoundRect(0,0,getWidth()-1,getHeight()-1,arc,arc);g.setColor(BORDER);g.drawRoundRect(0,0,getWidth()-1,getHeight()-1,arc,arc);g.dispose();super.paintComponent(graphics);}}
    private static final class StatusRenderer extends DefaultTableCellRenderer{public Component getTableCellRendererComponent(JTable t,Object value,boolean selected,boolean focus,int row,int column){JLabel label=(JLabel)super.getTableCellRendererComponent(t,value,selected,focus,row,column);boolean online="Online".equals(value);Color color=online?SUCCESS:new Color(0x9AA8BA);label.setIcon(IconManager.load(online?"monitor":"square",12,12,color));label.setIconTextGap(8);label.setForeground(online?new Color(0x07833A):MUTED);label.setFont(new Font("Segoe UI",Font.BOLD,13));return label;}}
}
